namespace: nexora-frontend

resources:
  - ../../../_base/workloads/frontend
  - external-secrets.yaml
  - ingress.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/nexoraua/nexora-frontend
    newTag: bootstrap
