namespace: nexora-frontend

resources:
  - ../../../_base/workloads/frontend
  - external-secrets.yaml
  - hpa.yaml
  - ingress.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/nexoraua/nexora-frontend
    newName: ghcr.io/nexoraua/nexora-frontend
    newTag: sha-c1b6a1ab84c1
    digest: sha256:ffde3347890efe1fd1b1444522f52ecf09d8adc81e487e07f11887d5bac371e9
