apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: nexora/develop/registry/ghcr
        property: username
    - secretKey: password
      remoteRef:
        key: nexora/develop/registry/ghcr
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexora-admin-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: nexora-admin-runtime
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__NexoraDb
      remoteRef:
        key: nexora/develop/apps/admin/runtime
        property: connection_string
    - secretKey: BlindIndex__PepperBase64
      remoteRef:
        key: nexora/develop/apps/admin/runtime
        property: blind_index_pepper_base64
    - secretKey: Vault__Token
      remoteRef:
        key: nexora/develop/apps/admin/runtime
        property: vault_token
