namespace: nexora-admin

resources:
- ../../../_base/workloads/admin
- external-secrets.yaml
- ingress.yaml

patches:
- path: deployment-patch.yaml

images:
- digest: sha256:546394d04266ef25450001db864a34bd0764f253070b173ad0117690e36305e9
  name: ghcr.io/nexoraua/nexora-admin
  newName: ghcr.io/nexoraua/nexora-admin
  newTag: sha-191181cb27ed
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
