namespace: nexora-admin

resources:
- ../../../_base/workloads/admin
- external-secrets.yaml
- ingress.yaml

patches:
- path: deployment-patch.yaml

images:
- digest: sha256:8ad84bd9f664b6b5f38d1f94d10c6873a274701816c46bc68ccce314cb5861c6
  name: ghcr.io/nexoraua/nexora-admin
  newName: ghcr.io/nexoraua/nexora-admin
  newTag: sha-051729f3da28
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
