apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: nexora/production/registry/ghcr
        property: username
    - secretKey: password
      remoteRef:
        key: nexora/production/registry/ghcr
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexora-api-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: nexora-api-runtime
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__NexoraDb
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: connection_string
    - secretKey: BlindIndex__PepperBase64
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: blind_index_pepper_base64
    - secretKey: Vault__Token
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: vault_token
    - secretKey: Auth__UserJwt__Authority
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_user_authority
    - secretKey: Auth__UserJwt__Issuer
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_user_issuer
    - secretKey: Auth__UserJwt__Audience
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_user_audience
    - secretKey: Auth__UserJwt__RequireHttpsMetadata
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_user_require_https_metadata
    - secretKey: Auth__AdminJwt__Authority
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_admin_authority
    - secretKey: Auth__AdminJwt__Issuer
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_admin_issuer
    - secretKey: Auth__AdminJwt__Audience
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_admin_audience
    - secretKey: Auth__AdminJwt__RequireHttpsMetadata
      remoteRef:
        key: nexora/production/apps/api/runtime
        property: auth_admin_require_https_metadata
