namespace: nexora-frontend

resources:
- ../../../_base/workloads/frontend
- external-secrets.yaml
- ingress.yaml

images:
- digest: sha256:970623a50ff8f084f050ff6cbd191bbf1f67789f4ade7fec052ebacf285cd8e0
  name: ghcr.io/nexoraua/nexora-frontend
  newName: ghcr.io/nexoraua/nexora-frontend
  newTag: sha-8538cbe636ed
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
