namespace: nexora-api

resources:
- ../../../_base/workloads/api
- external-secrets.yaml
- ingress.yaml

patches:
- path: deployment-patch.yaml

images:
- digest: sha256:b26ba8526f8c1f136c14bc47a9a7294d036ba9a71efe11597350309b730aac8b
  name: ghcr.io/nexoraua/nexora-api
  newName: ghcr.io/nexoraua/nexora-api
  newTag: sha-051729f3da28
- digest: sha256:2b481160f54bec9993ddcc729d18a00a868edc9d83ea27ec4833acfb0d6f8d78
  name: ghcr.io/nexoraua/nexora-migrator
  newName: ghcr.io/nexoraua/nexora-migrator
  newTag: sha-051729f3da28
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
