# RabbitMQ admin credentials.
# The RabbitMQ Cluster Operator expects a Secret named
# <cluster>-default-user when spec.secretBackend.externalSecret.name is
# set in the RabbitmqCluster CR. We mirror the same Secret name here.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: rabbitmq-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        # default_user.conf format consumed by RabbitMQ on boot.
        default_user.conf: |
          default_user = {{ .username }}
          default_pass = {{ .password }}
  data:
    - secretKey: username
      remoteRef:
        key: nexora/develop/rabbitmq/admin
        property: username
    - secretKey: password
      remoteRef:
        key: nexora/develop/rabbitmq/admin
        property: password
