apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-cache
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: data
  source:
    repoURL: https://github.com/nexora/nexora-gitops.git
    targetRevision: main
    path: clusters/develop/stateful/dragonfly
  destination:
    server: https://kubernetes.default.svc
    namespace: dragonfly
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
